/**
 * ADR-006 Phase 1 — Session State (`state.json`) schema + helpers
 *
 * The session directory layout is:
 *   ~/.thinklocal/sessions/<instance-uuid>/
 *     state.json        ← this file, written via writeAtomic
 *     HISTORY.md        ← regenerated by recovery-generator
 *     START-PROMPT.md   ← async LLM-generated (Phase 2)
 *     MEMORY.md         ← manually curated (Phase 3)
 *
 * `state.json` is the runtime anchor: the watcher and the binding
 * module read it to decide whether an instance is alive, which
 * native session file it listens to, and which byte offset it has
 * already consumed.
 *
 * See: docs/architecture/ADR-006-session-persistence.md §Architektur
 */
import { readFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { homedir } from 'node:os';
import { writeAtomic } from './atomic-write.js';

export interface SessionState {
  /** Stable identifier — matches ADR-005 per-agent-instance uuid. */
  readonly instanceUuid: string;
  /** OS process id of the live agent, or null when orphaned. */
  pid: number | null;
  /** ISO 8601 timestamp of session creation. */
  readonly startedAt: string;
  /** ISO 8601 timestamp of the most recent heartbeat / tail read. */
  lastHeartbeat: string;
  /** Working directory the agent was launched in. */
  readonly cwd: string;
  /** Git branch at launch time (best-effort, may be empty). */
  readonly gitBranch: string;
  /** `claude-code` / `codex` / `gemini-cli`. */
  readonly agentType: string;
  /**
   * Opaque session id assigned by the native CLI (e.g. the Claude
   * Code jsonl filename stem). Used by the adapter to find the
   * native file on disk.
   */
  readonly nativeSessionId: string | null;
  /** Byte offset into the native session file already consumed. */
  tailOffset: number;
  /**
   * Monotonic counter bumped on every HISTORY.md / START-PROMPT.md
   * regeneration. Readers can poll this to notice updates without
   * parsing the full file.
   */
  historyVersion: number;

  // --- ADR-009 Phase C PR C2: Goal-Context ---
  // These fields transport the "why" of a session, not just the "what".
  // The recovery-generator uses them to build a ## Goal & Status section
  // in HISTORY.md, so the next agent doesn't just see events but also
  // understands the purpose and current blockers.

  /** High-level goal of this session (e.g. "Implement ADR-007 Phase A"). */
  goal?: string;
  /** What success looks like (e.g. "3 PRs merged, tests green"). */
  expectedOutcome?: string;
  /** What is currently blocking progress (e.g. "Waiting for CR result"). */
  blockingReason?: string;
  /** Immediate next step (e.g. "Fix HIGH findings, then PC"). */
  nextAction?: string;
}

export function defaultSessionsRoot(dataDir?: string): string {
  return resolve(dataDir ?? resolve(homedir(), '.thinklocal'), 'sessions');
}

export function sessionDir(dataDir: string | undefined, instanceUuid: string): string {
  return resolve(defaultSessionsRoot(dataDir), instanceUuid);
}

export function stateFilePath(dataDir: string | undefined, instanceUuid: string): string {
  return resolve(sessionDir(dataDir, instanceUuid), 'state.json');
}

/**
 * Create or refresh the on-disk `state.json` for an instance.
 * Writes atomically — a crash mid-write cannot produce a corrupt
 * state file. Callers should bump `historyVersion` before invoking
 * this if they have also rewritten a derived-view file.
 */
export async function writeSessionState(
  dataDir: string | undefined,
  state: SessionState,
): Promise<void> {
  const path = stateFilePath(dataDir, state.instanceUuid);
  await mkdir(dirname(path), { recursive: true });
  const body = `${JSON.stringify(state, null, 2)}\n`;
  await writeAtomic(path, body);
}

/**
 * Read the state file. Returns `null` if it does not exist.
 * Throws on malformed JSON (the caller decides whether to treat
 * that as a fatal corruption or an orphan to be cleaned up).
 */
export async function readSessionState(
  dataDir: string | undefined,
  instanceUuid: string,
): Promise<SessionState | null> {
  const path = stateFilePath(dataDir, instanceUuid);
  if (!existsSync(path)) return null;
  const raw = await readFile(path, 'utf8');
  return JSON.parse(raw) as SessionState;
}

/**
 * Check whether a stored state's PID is still alive. Uses the
 * classic `kill(pid, 0)` trick which sends no signal but throws
 * ESRCH if the process is gone.
 */
export function isPidAlive(pid: number | null | undefined): boolean {
  if (!pid || pid <= 0) return false;
  try {
    process.kill(pid, 0);
    return true;
  } catch {
    return false;
  }
}
